(function(){
  'use strict';
  const STORAGE_KEY='progressions_ce2_suivi_v2';
  const state={subject:'francais',period:'all',mode:'suivi'};
  const grid=document.getElementById('progressionGrid');
  const title=document.getElementById('subjectTitle');
  const subtitle=document.getElementById('subjectSubtitle');
  const icon=document.getElementById('subjectIcon');
  const routines=document.getElementById('routinesList');
  const dashboard=document.getElementById('dashboard');
  const labels=['Période 1','Période 2','Période 3','Période 4','Période 5'];
  const classes=['p1','p2','p3','p4','p5'];
  const statusLabels={afaire:'À faire',encours:'En cours',travaille:'Travaillé',reprendre:'À reprendre',stabilise:'Stabilisé'};
  const masteryLabels={none:'Non évaluée',fragile:'Fragile',encours:'En cours d’acquisition',acquise:'Acquise',maitrisee:'Très bien maîtrisée'};
  let saved=loadSaved();

  function loadSaved(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')||{};}catch(e){return {};}}
  function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(saved));}catch(e){alert('La sauvegarde locale est impossible dans ce navigateur.');}}
  function key(subject,rowIndex,periodIndex){return `${subject}|${rowIndex}|${periodIndex}`;}
  function skillKey(code){return `skill|${code}`;}
  function entry(subject,rowIndex,periodIndex){const k=key(subject,rowIndex,periodIndex);if(!saved[k])saved[k]={status:'afaire',steps:{present:false,practice:false,reuse:false,check:false},retention:'',note:''};return saved[k];}
  function skillEntry(code,count){const k=skillKey(code);if(!saved[k])saved[k]={status:'afaire',checks:Array(count).fill(false),evaluation1:{label:'',date:'',result:'none'},evaluation2:{label:'',date:'',result:'none'},mastery:'none',note:''};if(!Array.isArray(saved[k].checks))saved[k].checks=Array(count).fill(false);while(saved[k].checks.length<count)saved[k].checks.push(false);return saved[k];}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function defaultRetention(domain,text){const clean=String(text||'').replace(/\s+/g,' ').trim();const first=clean.split(/(?<=[.!?])\s+/)[0].replace(/[.!]$/,'');const t={'Lecture — fluence':'Je sais lire à voix haute avec fluidité, respecter la ponctuation et mettre le ton.','Lecture — compréhension':'Je sais expliquer ce que j’ai compris et justifier mes réponses avec le texte.','Culture littéraire':'Je sais parler d’une œuvre, reconnaître son genre et faire des liens avec d’autres lectures.','Écriture — copie':'Je sais copier avec soin, respecter la présentation et me relire.','Production d’écrits':'Je sais organiser mes idées, écrire un texte cohérent puis l’améliorer.','Oral':'Je sais écouter, prendre la parole clairement et respecter les échanges.','Vocabulaire':'Je sais comprendre, classer et réutiliser des mots nouveaux.','Grammaire — phrase':'Je sais observer une phrase et utiliser les mots de la grammaire pour l’analyser.','Conjugaison':'Je sais reconnaître le temps d’un verbe et conjuguer les verbes étudiés.','Orthographe grammaticale':'Je sais raisonner pour réaliser les accords étudiés.','Orthographe lexicale — dictée':'Je sais mémoriser l’orthographe des mots et utiliser des régularités pour écrire.','Nombres entiers':'Je sais lire, écrire, comparer et décomposer les nombres étudiés.','Fractions':'Je sais représenter, nommer et comparer les fractions étudiées.','Calcul mental':'Je sais choisir une stratégie de calcul mental efficace.','Calcul posé — opérations':'Je sais poser une opération, estimer et vérifier mon résultat.','Résolution de problèmes':'Je sais comprendre un problème, choisir une représentation et expliquer ma démarche.','Longueurs — périmètres':'Je sais mesurer, choisir une unité et résoudre des problèmes de longueur ou de périmètre.','Masses — contenances':'Je sais mesurer, comparer et choisir une unité adaptée.','Monnaie — durées':'Je sais utiliser la monnaie et calculer des durées dans des situations simples.','Géométrie plane':'Je sais reconnaître, décrire et construire les figures étudiées.','Symétrie':'Je sais reconnaître un axe et compléter une figure symétrique.','Solides':'Je sais reconnaître, décrire et représenter les solides étudiés.','Données':'Je sais lire, organiser et interpréter des données dans un tableau ou un graphique.'};return t[domain]||`Je sais expliquer et utiliser ce que j’ai appris : ${first}.`;}

  function currentSkills(){if(state.mode!=='suivi')return null;const data=window.PROGRESSIONS[state.subject];const map={p1:'p1Competencies',p2:'p2Competencies',p3:'p3Competencies',p4:'p4Competencies',p5:'p5Competencies'};const key=map[state.period];return key?(data[key]||[]):null;}
  function render(){const data=window.PROGRESSIONS[state.subject];title.textContent=data.title;subtitle.textContent=data.subtitle;icon.textContent=data.icon;document.getElementById('currentPeriodLabel').textContent=state.period==='all'?'Vue annuelle':labels[classes.indexOf(state.period)];document.getElementById('currentModeLabel').textContent=state.mode==='suivi'?'Mon suivi':'Référentiel';document.getElementById('compactSubject').textContent=data.title;document.getElementById('compactPeriod').textContent=state.period==='all'?'Vue annuelle':labels[classes.indexOf(state.period)];showCategory(subjectCategory(state.subject));routines.innerHTML=data.routines.map(x=>`<li>${esc(x)}</li>`).join('');dashboard.classList.toggle('hidden',state.mode!=='suivi');grid.classList.toggle('is-followup',state.mode==='suivi');if(state.mode==='reference')renderReference(data);else if(state.subject==='parcours')renderFollowup(data);else{const skills=currentSkills();if(skills)renderSkills(skills);else renderFollowup(data);}updateDashboard();}
  function renderReference(data){grid.innerHTML=data.rows.map(row=>{if(state.period==='all')return `<article class="domain-card"><h3 class="domain-title">${esc(row[0])}</h3><div class="annual-grid">${row.slice(1).map((text,i)=>`<section class="period-cell ${classes[i]}"><h4>${labels[i]}</h4><p>${esc(text)}</p></section>`).join('')}</div></article>`;const i=classes.indexOf(state.period);return `<article class="domain-card"><h3 class="domain-title">${esc(row[0])}</h3><div class="single-period ${state.period}">${esc(row[i+1])}</div></article>`;}).join('');}
  function renderFollowup(data){const ps=state.period==='all'?[0,1,2,3,4]:[classes.indexOf(state.period)];grid.innerHTML=data.rows.map((row,ri)=>`<article class="domain-card followup-domain"><h3 class="domain-title">${esc(row[0])}</h3><div class="followup-periods ${state.period==='all'?'all':''}">${ps.map(pi=>followupCard(row,ri,pi)).join('')}</div></article>`).join('');bindFollowupEvents();}
  function followupCard(row,ri,pi){const e=entry(state.subject,ri,pi);const isParcours=state.subject==='parcours';const retention=e.retention||(isParcours?'Projet ou action :\nMatières / partenaires :\nTrace LSU :':defaultRetention(row[0],row[pi+1]));const checklist=isParcours?`${step('present','Projet ou action défini',e.steps.present)}${step('practice','Matières, partenaires ou ressources renseignés',e.steps.practice)}${step('reuse','Action réellement menée',e.steps.reuse)}${step('check','Trace LSU rédigée',e.steps.check)}`:`${step('present','Notion présentée',e.steps.present)}${step('practice','Entraînement réalisé',e.steps.practice)}${step('reuse','Réinvestissement prévu ou réalisé',e.steps.reuse)}${step('check','Vérification ou observation réalisée',e.steps.check)}`;const retentionTitle=isParcours?'📘 Mémoire du projet et trace LSU':'🦉 Je sais / J’ai retenu';const notePlaceholder=isParcours?'Dates, production, sortie, rencontre, bilan…':'Adaptation, difficulté, reprise, projet…';return `<section class="followup-card ${classes[pi]}" data-key="${key(state.subject,ri,pi)}"><div class="followup-head"><span>${labels[pi]}</span><select class="status-select status-${e.status}">${options(statusLabels,e.status)}</select></div><p class="planned"><strong>Cadre proposé</strong>${esc(row[pi+1])}</p><fieldset class="checklist"><legend>Ma checklist</legend>${checklist}</fieldset><label class="retention"><span>${retentionTitle}</span><textarea data-field="retention" rows="4">${esc(retention)}</textarea></label><label class="teacher-note"><span>📝 Ma note</span><textarea data-field="note" rows="2" placeholder="${notePlaceholder}">${esc(e.note)}</textarea></label></section>`;}
  function options(obj,current){return Object.entries(obj).map(([v,l])=>`<option value="${v}" ${current===v?'selected':''}>${l}</option>`).join('');}
  function step(n,l,c){return `<label class="check-row"><input type="checkbox" data-step="${n}" ${c?'checked':''}><span>${l}</span></label>`;}

  function renderSkills(skills){const groups={};skills.forEach(s=>(groups[s.domain]||(groups[s.domain]=[])).push(s));const periodLabel=`période ${classes.indexOf(state.period)+1}`;grid.innerHTML=`<section class="skill-intro card"><strong>${esc(window.PROGRESSIONS[state.subject].title)} — ${periodLabel} : ${skills.length} compétences précises</strong><span>La checklist guide le travail. Une ou deux évaluations seulement sont retenues comme preuves. Le bilan alimente la synthèse LSU.</span></section>`+Object.entries(groups).map(([domain,list])=>`<article class="domain-card skill-domain"><h3 class="domain-title">${esc(domain)} <small>${list.length} compétence${list.length>1?'s':''}</small></h3><div class="skill-grid">${list.map(skillCard).join('')}</div></article>`).join('');bindSkillEvents();}
  function skillCard(s){const e=skillEntry(s.code,s.checklist.length);return `<details class="skill-card" data-code="${esc(s.code)}"><summary><span class="skill-code">${esc(s.code)}</span><span class="skill-title">${esc(s.title)}</span><span class="skill-state status-${e.status}">${esc(statusLabels[e.status])}</span></summary><div class="skill-body"><div class="skill-top"><label><span>Suivi de l’enseignement</span><select data-skill-field="status" class="status-select status-${e.status}">${options(statusLabels,e.status)}</select></label><label><span>Bilan de la compétence</span><select data-skill-field="mastery" class="mastery-select mastery-${e.mastery}">${options(masteryLabels,e.mastery)}</select></label></div><blockquote class="je-sais"><strong>🦉 Je sais</strong>${esc(s.jeSais)}</blockquote><fieldset class="checklist skill-checklist"><legend>Checklist pédagogique</legend>${s.checklist.map((x,i)=>`<label class="check-row"><input type="checkbox" data-check-index="${i}" ${e.checks[i]?'checked':''}><span>${esc(x)}</span></label>`).join('')}</fieldset><div class="proofs"><strong>Preuves possibles</strong><ul>${s.proofs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="evaluations"><h4>Évaluations retenues — une ou deux maximum</h4>${evaluationRow(1,e.evaluation1,s.proofs[0])}${evaluationRow(2,e.evaluation2,s.proofs[1])}</div><div class="lsu-box"><strong>Regroupement LSU</strong><span>${esc(s.lsu)}</span></div><label class="teacher-note"><span>📝 Ma note</span><textarea data-skill-field="note" rows="2" placeholder="Adaptation, difficulté, reprise…">${esc(e.note)}</textarea></label></div></details>`;}
  function evaluationRow(n,e,placeholder){return `<div class="evaluation-row"><label><span>Évaluation ${n}${n===2?' (facultative)':''}</span><input type="text" data-eval="${n}" data-eval-field="label" value="${esc(e.label)}" placeholder="${esc(placeholder||'Situation retenue')}"></label><label><span>Date</span><input type="date" data-eval="${n}" data-eval-field="date" value="${esc(e.date)}"></label><label><span>Résultat</span><select data-eval="${n}" data-eval-field="result">${options(masteryLabels,e.result||'none')}</select></label></div>`;}

  function bindFollowupEvents(){grid.querySelectorAll('.followup-card').forEach(card=>{const e=saved[card.dataset.key];const select=card.querySelector('.status-select');select.addEventListener('change',()=>{e.status=select.value;select.className=`status-select status-${e.status}`;persist();updateDashboard();});card.querySelectorAll('[data-step]').forEach(i=>i.addEventListener('change',()=>{e.steps[i.dataset.step]=i.checked;persist();updateDashboard();}));card.querySelectorAll('[data-field]').forEach(a=>a.addEventListener('input',()=>{e[a.dataset.field]=a.value;persist();}));});}
  function bindSkillEvents(){grid.querySelectorAll('.skill-card').forEach(card=>{const code=card.dataset.code;const skill=(currentFrenchSkills()||[]).find(x=>x.code===code);const e=skillEntry(code,skill.checklist.length);card.querySelectorAll('[data-check-index]').forEach(i=>i.addEventListener('change',()=>{e.checks[Number(i.dataset.checkIndex)]=i.checked;persist();updateDashboard();}));card.querySelectorAll('[data-skill-field]').forEach(el=>{const evt=el.tagName==='TEXTAREA'?'input':'change';el.addEventListener(evt,()=>{e[el.dataset.skillField]=el.value;if(el.dataset.skillField==='status'){el.className=`status-select status-${e.status}`;card.querySelector('.skill-state').className=`skill-state status-${e.status}`;card.querySelector('.skill-state').textContent=statusLabels[e.status];}if(el.dataset.skillField==='mastery')el.className=`mastery-select mastery-${e.mastery}`;persist();updateDashboard();});});card.querySelectorAll('[data-eval]').forEach(el=>{const evt=el.tagName==='INPUT'?'input':'change';el.addEventListener(evt,()=>{const target=Number(el.dataset.eval)===1?e.evaluation1:e.evaluation2;target[el.dataset.evalField]=el.value;persist();});});});}
  function visibleKeys(){const skills=currentFrenchSkills();if(skills)return skills.map(s=>skillKey(s.code));const data=window.PROGRESSIONS[state.subject],ps=state.period==='all'?[0,1,2,3,4]:[classes.indexOf(state.period)],keys=[];data.rows.forEach((_,ri)=>ps.forEach(pi=>keys.push(key(state.subject,ri,pi))));return keys;}
  function updateDashboard(){if(state.mode!=='suivi')return;const counts={afaire:0,encours:0,travaille:0,reprendre:0,stabilise:0};const keys=visibleKeys();keys.forEach(k=>{const e=saved[k]||{status:'afaire'};counts[e.status]=(counts[e.status]||0)+1;});const done=counts.travaille+counts.stabilise;const percent=keys.length?Math.round(done/keys.length*100):0;document.getElementById('progressPercent').textContent=percent+' %';document.getElementById('progressBar').style.width=percent+'%';document.getElementById('stats').innerHTML=Object.entries(statusLabels).map(([k,l])=>`<div class="stat stat-${k}"><strong>${counts[k]||0}</strong><span>${l}</span></div>`).join('');}

  function subjectCategory(subject){
    const map={francais:'fondamentaux',maths:'fondamentaux',histoire:'monde',geographie:'monde',sciences:'monde',anglais:'anglais',arts:'anglais',eps:'anglais',emc:'citoyennete',evar:'citoyennete',parcours:'citoyennete',emi:'emi'};
    return map[subject]||'fondamentaux';
  }
  function showCategory(category){
    document.querySelectorAll('.category-tab').forEach(b=>b.classList.toggle('is-active',b.dataset.category===category));
    document.querySelectorAll('.family-group').forEach(g=>g.classList.toggle('is-active',g.dataset.category===category));
    const secondary=document.querySelector('.subject-tabs--secondary');
    document.querySelectorAll('.subject-tabs--secondary .tab').forEach(b=>b.classList.toggle('is-hidden',b.dataset.category!==category));
    if(secondary) secondary.classList.toggle('is-empty',category==='fondamentaux');
  }
  document.querySelectorAll('.category-tab').forEach(btn=>btn.addEventListener('click',()=>{
    const category=btn.dataset.category;
    showCategory(category);
    const first=document.querySelector(`.subject-tabs--secondary .tab[data-category="${category}"]`);
    if(first){
      document.querySelectorAll('.tab').forEach(b=>b.classList.remove('is-active'));
      first.classList.add('is-active');
      state.subject=first.dataset.subject;
      render();
      if(!filtersPinned)setFiltersOpen(false);
    }
  }));
  showCategory(subjectCategory(state.subject));
  document.getElementById('printBtn').addEventListener('click',()=>window.print());
  document.getElementById('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:5,exportedAt:new Date().toISOString(),data:saved},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sauvegarde_progressions_ce2.json';a.click();URL.revokeObjectURL(a.href);});
  document.getElementById('importInput').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);saved=p.data||p;persist();render();alert('Sauvegarde importée.');}catch(e){alert('Ce fichier de sauvegarde n’est pas valide.');}};r.readAsText(file);event.target.value='';});
  document.getElementById('resetBtn').addEventListener('click',()=>{if(!confirm('Réinitialiser uniquement la matière et la période actuellement affichées ?'))return;visibleKeys().forEach(k=>delete saved[k]);persist();render();});
  render();
})();
