(()=>{'use strict';
const $=id=>document.getElementById(id), student=$('hibouStudent'), semester=$('hibouSemester'), refresh=$('hibouRefresh'), status=$('hibouStatus'), body=$('hibouBody'), summary=$('hibouSummary'), legacyCard=$('legacyCard'), legacyText=$('legacyText'), legacyList=$('legacyList');
let snapshot=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=v=>String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ');
function cfg(){return window.LSURealConnector?.getBrowserConfig?.()||{url:'',key:''}}
function jsonp(params,timeoutMs=60000){return new Promise((resolve,reject)=>{const c=cfg();if(!c.url||!c.key)return reject(new Error('Connexion Maître Hibou non configurée sur cet appareil.'));const cb='hibouSkills_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const end=(err,data)=>{if(done)return;done=true;clearTimeout(timer);try{s.remove()}catch{};try{delete globalThis[cb]}catch{};err?reject(err):resolve(data)};const timer=setTimeout(()=>end(new Error('Délai de connexion dépassé.')),timeoutMs);globalThis[cb]=data=>end(data&&data.ok===false?new Error(data.error||'Réponse invalide'):null,data);const q=new URLSearchParams({...params,device_key:c.key,tablet_key:c.key,key:c.key,callback:cb,_:Date.now()});s.src=c.url+'?'+q.toString();s.onerror=()=>end(new Error('API Maître Hibou indisponible.'));document.head.appendChild(s);});}
function isHibou(r){const s=norm(r?.source);return s.includes('hibou')||s.includes('ceinture')||!!String(r?.mastery_status||'').trim()}
function sem(r){return LSURealConnector.semesterOfRow(r)||''}
function dateLabel(v){const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleDateString('fr-FR'):String(v||'—')}
function resultKind(r){const m=norm(r?.mastery_status||r?.resultat||r?.texte);if(m.includes('avec aide'))return'help';if(m.includes('reussi')||m.includes('maitrise'))return'good';return''}
function resultText(r){const m=norm(r?.mastery_status);let t='Trace enregistrée';if(m.includes('maitrise plusieurs'))t='⭐ Maîtrisé plusieurs fois';else if(m.includes('avec aide'))t='🟡 Réussi avec aide';else if(m.includes('reussi seul')||m==='reussi')t='✅ Réussi seul';else if(m.includes('renforcer'))t='🔴 À renforcer';else if(norm(r?.resultat).includes('reussite')||norm(r?.resultat).includes('reussi'))t='✅ Réussi';const score=String(r?.score??'').trim(), total=String(r?.total??'').trim();if(score&&total)t+=` — ${score}/${total}`;return t}
function rows(){const snap=snapshot?.snapshot||snapshot||{}, all=(snap.reussites||[]).filter(isHibou), seen=new Set();return all.filter(r=>{const id=String(r.event_id||[r.date,r.competence_code,r.activite,r.score,r.source].join('|'));if(seen.has(id))return false;seen.add(id);return true}).sort((a,b)=>Date.parse(b.date||0)-Date.parse(a.date||0));}
function render(){const all=rows(), coded=all.filter(r=>String(r.competence_code||'').trim()), legacy=all.filter(r=>!String(r.competence_code||'').trim()), f=semester.value, shown=f==='ALL'?coded:coded.filter(r=>sem(r)===f);const latestByCode=new Map();coded.forEach(r=>{const c=String(r.competence_code).trim();if(!latestByCode.has(c))latestByCode.set(c,r)});const latest=[...latestByCode.values()], alone=latest.filter(r=>norm(r.mastery_status).includes('reussi seul')||norm(r.mastery_status).includes('maitrise plusieurs')).length, help=latest.filter(r=>norm(r.mastery_status).includes('avec aide')).length, s1=latest.filter(r=>sem(r)==='S1').length, s2=latest.filter(r=>sem(r)==='S2').length;
summary.innerHTML=`<div class="summary-line"><strong>${latest.length}</strong> compétence${latest.length>1?'s':''} observée${latest.length>1?'s':''} dans Maître Hibou</div><div class="summary-meta">${alone} réussie${alone>1?'s':''} seule${alone>1?'s':''} · ${help} réussie${help>1?'s':''} avec aide</div><div class="summary-pills"><span class="pill good">✅ Réussies seules : ${alone}</span><span class="pill help">🟡 Avec aide : ${help}</span><span class="pill">S1 : ${s1}</span><span class="pill">S2 : ${s2}</span></div>`;
body.innerHTML=shown.length?shown.map(r=>`<tr><td>${esc(dateLabel(r.date))}</td><td><span class="skill-code">${esc(r.competence_code)}</span> — ${esc(r.competence_label||r.activite||'Compétence')}</td><td class="result ${resultKind(r)}">${esc(resultText(r))}</td><td class="semester">${esc(sem(r)||'—')}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">Aucune compétence codée pour ce filtre.</td></tr>';
legacyCard.hidden=!legacy.length;if(legacy.length){legacyText.textContent=`${legacy.length} ancienne(s) réussite(s) sont conservée(s) dans le Sheet mais ne disposent pas encore d’un code canonique. Elles restent visibles ici sans être utilisées pour le LSU.`;legacyList.innerHTML=legacy.slice(0,100).map(r=>`<div class="legacy-row"><span>${esc(dateLabel(r.date))}</span><span>${esc(r.activite||r.texte||'Ancienne trace')}</span><strong>${esc(r.score??'')}${r.total?'/'+esc(r.total):''}</strong></div>`).join('')}}
async function loadStudents(){status.textContent='Chargement des élèves…';try{const data=await jsonp({action:'get_eleves'}), arr=Array.isArray(data)?data:(data.students||data.eleves||[]), names=arr.map(r=>String(r.prenom||r.name||'').trim()).filter(Boolean);student.innerHTML=names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');status.textContent=`${names.length} élèves disponibles.`;if(names.length)await loadSnapshot()}catch(e){status.textContent='Impossible de charger les élèves : '+e.message}}
async function loadSnapshot(){const name=student.value;if(!name)return;refresh.disabled=true;status.textContent=`Chargement des compétences de ${name}…`;try{snapshot=await LSURealConnector.getStudentSnapshot(name);render();status.textContent=`Compétences de ${name} actualisées.`}catch(e){snapshot=null;body.innerHTML='<tr><td colspan="4" class="empty">Impossible de charger les données.</td></tr>';summary.innerHTML='<div class="summary-empty">'+esc(e.message)+'</div>';status.textContent='Erreur : '+e.message}finally{refresh.disabled=false}}
student.addEventListener('change',loadSnapshot);semester.addEventListener('change',()=>snapshot&&render());refresh.addEventListener('click',loadSnapshot);loadStudents();
})();
