window.PROGRESSIONS = {
  francais: {
    title: "Français", icon: "📘", subtitle: "Lecture, écriture, oral, vocabulaire, grammaire et orthographe",
    routines: ["Lecture silencieuse et orale chaque jour","Fluence évaluée régulièrement","Écriture et copie chaque jour","Vocabulaire explicite quotidien ; environ 6 corpus par période","Grammaire et orthographe : enseignement explicite et réinvestissement","5 à 10 œuvres sur l’année"],
    rows: [
      ["Lecture — fluence","Évaluation diagnostique. Lecture orale quotidienne. Respect de la ponctuation. Groupes de sens. Automatismes sur mots fréquents.","Gagner en exactitude et en vitesse. Lire des textes variés. Préparer puis relire à voix haute.","Fluidité, liaisons, intonation. Lecture dialoguée. Suivi régulier de la fluence.","Lecture expressive. Mise en voix de poèmes, dialogues et courts textes documentaires.","Consolider une lecture autonome, fluide et expressive. Bilan et objectifs individuels."],
      ["Lecture — compréhension","Repérer personnages, lieux, chronologie et informations explicites. Reformuler l’essentiel.","Comprendre un mot en contexte. Identifier les reprises nominales et pronominales.","Hiérarchiser les informations. Produire des inférences simples. Justifier avec le texte.","Comprendre l’implicite, les intentions et les relations de cause à conséquence.","Mobiliser les stratégies apprises sur récits, documents, poèmes et théâtre. Synthétiser."],
      ["Culture littéraire","Contes et récits courts. Construire des habitudes de lecteur.","Récits d’aventure et textes documentaires. Comparer textes et illustrations.","Récits patrimoniaux, mythes ou légendes adaptés. Réseaux autour d’un thème.","Poésie et théâtre. Mise en voix et mémorisation.","Œuvre longue ou réseau final. Carnet de lecteur et bilan du parcours."],
      ["Écriture — copie","Automatiser les minuscules et majuscules cursives. Copie courte, lisible et fidèle.","Copie par groupes de mots. Respect de la mise en page. Premières copies différées.","Copier un texte plus long avec stratégie de mémorisation et contrôle.","Copie différée, prise d’informations et mise en page complexe.","Copie autonome et révision des stratégies efficaces."],
      ["Production d’écrits","Écrire des phrases puis un court paragraphe à partir d’une image ou d’un vécu. Ponctuer.","Raconter dans l’ordre. Écrire une lettre ou un dialogue court. Enrichir les phrases.","Décrire un personnage ou un lieu. Employer connecteurs temporels et substituts.","Résumer, raconter une sortie, écrire un documentaire ou un poème.","Écrire la suite d’un récit ou un texte long en plusieurs paragraphes. Réviser et publier."],
      ["Oral","Écouter, reformuler une consigne, raconter brièvement et participer à un échange réglé.","Présenter une démarche. Poser des questions pertinentes. Respecter les tours de parole.","Raconter avec précision. Expliquer et justifier un choix.","Débat court, exposé préparé, lecture expressive et jeu théâtral.","Présentation orale structurée. Réinvestir vocabulaire et syntaxe adaptés."],
      ["Vocabulaire","Dictionnaire, ordre alphabétique, mots génériques et spécifiques. Corpus 1 à 6.","Familles de mots, radical, préfixes et suffixes. Synonymes et contraires.","Polysémie et niveaux de langue. Réseaux lexicaux et échelles d’intensité.","Sens propre et sens figuré. Expressions et associations fréquentes.","Réinvestir les réseaux. Morphologie, familles de mots, catégorisation et bilan lexical."],
      ["Grammaire — phrase","Phrase, ponctuation, trois types de phrases, formes négative et exclamative. Verbe et groupe sujet.","Pronoms personnels sujets. Nom commun et nom propre. Relation sujet-verbe.","Groupe nominal : déterminant, nom, adjectif. Accords dans le groupe nominal.","Compléments de la phrase sans nomenclature excessive. Adverbe. Manipulations syntaxiques.","Consolider l’analyse de la phrase simple : sujet, verbe, compléments et classes étudiées."],
      ["Conjugaison","Passé, présent, futur. Infinitif, radical, terminaison. Présent des verbes en -er et être/avoir.","Présent des verbes fréquents : aller, faire, dire, venir, voir. Réinvestissement quotidien.","Futur des verbes en -er et verbes fréquents. Marques régulières des personnes.","Imparfait des verbes en -er, être, avoir et verbes fréquents.","Passé composé des verbes en -er et verbes fréquents. Synthèse des quatre temps."],
      ["Orthographe grammaticale","Accord sujet-verbe dans les cas simples. Pluriel des noms. Homophones a/à, et/est.","Accord déterminant-nom. Marques du pluriel. Homophones son/sont, on/ont, ou/où.","Accord dans le groupe nominal avec adjectif. Féminin et pluriel des noms et adjectifs.","Consolider les accords. Lettres finales muettes. Infinitif en -er et participe en -é.","Accords dans la phrase et le groupe nominal. Révision raisonnée des homophones en contexte."],
      ["Orthographe lexicale — dictée","Graphèmes complexes et mots fréquents. Dictée courte, négociée et préparée.","s/ss, c/ç, g/ge/gu. Morphologie lexicale et mots invariables.","m devant m, b, p ; accents ; analogies et familles de mots.","Pluriels particuliers les plus fréquents. Copie et dictée avec relecture guidée.","Révision des régularités, mots irréguliers fréquents et dictées de synthèse."]
    ]
  },
  maths: {
    title: "Mathématiques", icon: "📐", subtitle: "Nombres, calcul, problèmes, grandeurs, mesures, géométrie et données",
    routines: ["Calcul mental quotidien","Résolution de problèmes fréquente et explicite","Manipulation, verbalisation et représentations","Réactivation des acquis à chaque période","Données et grandeurs intégrées aux problèmes","Évaluation courte et régulation en fin de période"],
    rows: [
      ["Nombres entiers","Nombres au-delà de 1 000 dès le début. Lire, écrire, décomposer, comparer, encadrer. Relations unités/dizaines/centaines/milliers.","Étendre jusqu’à 10 000 au plus tard. Différentes écritures, valeur des chiffres, droite graduée.","Dénombrements complexes et conversions entre unités de numération. Intercaler et ordonner.","Consolider jusqu’à 10 000. Résoudre des problèmes mobilisant la numération.","Synthèse, automatismes, estimation et réinvestissement dans toutes les situations."],
      ["Fractions","Réinvestir demi, tiers, quart, dixième comme fractions d’un tout. Représenter et nommer.","Égalités simples entre fractions inférieures ou égales à 1. Comparer par manipulation.","À partir de P3 : fractions d’une unité de longueur. Mesurer et tracer des longueurs non entières.","Placer, comparer et ordonner des fractions. Additions et soustractions simples avec représentations.","Fractions de nombres entiers dans des cas simples. Synthèse avec dénominateur inférieur ou égal à 12."],
      ["Calcul mental","Tables d’addition dans les deux sens. Compléments à 10 et 100. Ajouter ou retrancher 9, 19, 29…","Doubles et moitiés usuels. Multiplier par 10 et 100. Stratégies additives.","Tables de multiplication : mémorisation progressive. Multiplier par 4 ou 8.","Produits d’un nombre à deux chiffres par un chiffre en décomposant. Quotients simples.","Automatisation et choix de la stratégie la plus efficace. Rebrassage quotidien."],
      ["Calcul posé — opérations","Addition et soustraction posées : sens, estimation et contrôle du résultat.","Consolider addition et soustraction. Vocabulaire somme, différence, termes.","Multiplication posée par un chiffre puis par des dizaines simples. Produit, facteur, multiple.","Multiplication d’un nombre à 2 ou 3 chiffres par un nombre à 1 ou 2 chiffres. Sens de la division.","Quatre opérations en contexte. Choisir l’opération, estimer et vérifier."],
      ["Résolution de problèmes","Problèmes additifs et soustractifs à une ou deux étapes. Schématiser et expliciter.","Problèmes multiplicatifs, groupement et partage. Problèmes mixtes.","Comparaison multiplicative, monnaie et fractions simples. Deux ou trois étapes.","Problèmes de mesures, périmètre, durées et organisation de données.","Problèmes complexes et atypiques. Choisir une représentation, rédiger et contrôler."],
      ["Longueurs — périmètres","Mesurer et tracer en cm et mm. Estimer, comparer, utiliser des références.","Relations mm-cm-dm-m. Déterminer le périmètre par mesurage, sans formule imposée.","Choisir l’unité adaptée. Fractions d’unité de longueur.","Calculer et comparer des périmètres. Résoudre des problèmes.","Conversions et problèmes de synthèse."],
      ["Masses — contenances","Comparer des objets et construire des références de masse et de contenance.","Mesurer des masses : g, kg. Estimer et comparer.","Mesurer des contenances : L, dL, cL selon les situations.","Relations kg-g et unités usuelles. Choisir l’unité adaptée.","Conversions et problèmes à plusieurs étapes."],
      ["Monnaie — durées","Utiliser euros et billets. Résoudre des problèmes simples d’achat.","Euros et centimes. Lire l’heure entière et en minutes.","Heure, demi-heure, quart d’heure ; placer les aiguilles.","Rendre la monnaie. Mesurer une durée écoulée simple.","Comparer et calculer des durées. Problèmes à une ou deux étapes."],
      ["Géométrie plane","Point, droite, segment, alignement. Règle et équerre. Angle droit. Carré et rectangle.","Polygones, côtés, sommets, angles, diagonales. Décrire et reproduire.","Triangles et triangle rectangle. Construire carré, rectangle et triangle sur papier uni ou quadrillé.","Cercle et disque : centre, rayon, diamètre. Programmes de construction.","Consolider les figures, propriétés et constructions complexes."],
      ["Symétrie","Repérer intuitivement des figures symétriques par pliage.","Reconnaître un axe sur des figures usuelles.","Tracer des axes sur quadrillage ou papier pointé.","Compléter une figure par rapport à un axe vertical ou horizontal.","Réinvestir dans des frises, pavages et programmes de construction."],
      ["Solides","Manipuler et décrire des solides usuels.","Reconnaître cube, pavé, boule, cylindre, cône et pyramide.","Faces, arêtes, sommets ; polyèdre et non-polyèdre.","Assembler des solides à partir d’un modèle ; comparer objet et représentation.","Patrons simples du cube et du pavé. Construction et synthèse."],
      ["Données","Recueillir des données et lire un tableau simple ou à double entrée.","Construire et compléter un tableau à double entrée.","Lire et produire un diagramme en barres avec échelle adaptée.","Résoudre des problèmes à partir de tableaux et diagrammes.","Enquête de classe : collecte, tableau, diagramme, interprétation et communication."]
    ]
  }
};
