(()=>{
'use strict';
const $=id=>document.getElementById(id);
const semester=$('lsuSemester'), subject=$('lsuSubject'), runClass=$('lsuRunClass'), status=$('lsuStatus'), classBody=$('lsuClassBody'), classKpis=$('classKpis');
const detail=$('studentDetail'), detailTitle=$('detailTitle'), detailApp=$('detailAppreciation'), detailPos=$('detailPosition'), sources=$('lsuSources'), semesterProof=$('semesterProof'), history=$('competenceHistory');
let students=[],reports=new Map(),snapshots=new Map();
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function norm(v){return String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ')}
function cfg(){return window.LSURealConnector?.getBrowserConfig?.()||{url:'',key:''};}
function jsonp(params,timeoutMs=60000){return new Promise((resolve,reject)=>{const c=cfg();if(!c.url||!c.key)return reject(new Error('Connexion Maître Hibou non configurée sur cet appareil.'));const cb='lsuUI_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const end=(err,data)=>{if(done)return;done=true;clearTimeout(timer);try{s.remove()}catch{};try{delete globalThis[cb]}catch{};err?reject(err):resolve(data)};const timer=setTimeout(()=>end(new Error('Délai de connexion dépassé.')),timeoutMs);globalThis[cb]=data=>end(data&&data.ok===false?new Error(data.error||'Réponse invalide'):null,data);const q=new URLSearchParams({...params,device_key:c.key,tablet_key:c.key,key:c.key,callback:cb,_:Date.now()});s.src=c.url+'?'+q.toString();s.onerror=()=>end(new Error('API Maître Hibou indisponible.'));document.head.appendChild(s);});}
function labelConfidence(v){return({elevee:'Élevée',moyenne:'Moyenne',faible:'Faible',insuffisante:'Insuffisante'})[v]||v||'—'}
function subjectTitle(){return subject.options[subject.selectedIndex]?.text||subject.value}
function subjectMatches(row,key){const m=norm(row?.matiere),a=norm(row?.activite),code=String(row?.competence_code||'').toUpperCase();const map={francais:['francais','grammaire','lecture','ecriture','orthographe','vocabulaire'],maths:['math','mathematique','calcul','numeration','geometrie'],anglais:['anglais','english'],histoire:['histoire'],geographie:['geographie'],sciences:['science'],emc:['emc','vivre ensemble'],eps:['eps','sport'],arts:['arts','musique','chant','education musicale']};return (map[key]||[key]).some(x=>m.includes(norm(x))||a.includes(norm(x)))||({francais:/^(OR|LEC|COM|ECR|GRA|ORT|VOC)-/,maths:/^(NUM|CAL|PRO|GEO|MES|DON)-/,anglais:/^ANG-/,histoire:/^HIS-/,geographie:/^GEO-/,sciences:/^SCI-/,emc:/^EMC-/,eps:/^EPS-/,arts:/^(ART|MUS)-/}[key]?.test(code));}
function semesterOf(row){return window.LSURealConnector.semesterOfRow(row)||''}
function isHibou(row){const s=norm(row?.source);return s.includes('hibou')||s.includes('ceinture')||!!String(row?.mastery_status||'').trim()}
function isSuccess(row){const r=norm(row?.resultat||row?.mastery_status||row?.texte);return r.includes('reussi')||r.includes('maitrise')||Number(row?.score)>=Number(row?.total||Infinity)*.75}
function traceLabel(row){return row?.competence_label||row?.activite||row?.texte||row?.competence_code||'Trace enregistrée'}
function sourceLabel(row){if(isHibou(row))return'🦉 Maître Hibou';const s=norm(row?.source);if(s.includes('cahier')||s.includes('format')||s.includes('observation'))return'📝 Observation de classe';return'🏫 Évaluation de référence'}
function formatDate(v){const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleDateString('fr-FR'):String(v||'—')}
function usablePhrase(r){return r&&r.suggestedLevel&&r.confidence!=='insuffisante'&&r.phrase&&!/^Données insuffisantes/i.test(r.phrase)}
async function copyText(text,btn){try{await navigator.clipboard.writeText(text);const old=btn.textContent;btn.textContent='✓ Copié';setTimeout(()=>btn.textContent=old,1200)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();}}
async function loadStudents(){status.textContent='Chargement des élèves…';try{const data=await jsonp({action:'get_eleves'}),rows=Array.isArray(data)?data:(data.students||data.eleves||[]);students=rows.map(r=>String(r.prenom||r.name||'').trim()).filter(Boolean);status.textContent=students.length?`${students.length} élèves disponibles.`:'Aucun élève trouvé.';}catch(e){status.textContent='Impossible de charger la liste : '+e.message;}}
function rowHtml(name,state){if(state.loading)return`<tr data-name="${esc(name)}"><td class="student-name">${esc(name)}</td><td class="app-cell">Analyse en cours…</td><td>—</td><td>—</td><td>—</td></tr>`;if(state.error)return`<tr data-name="${esc(name)}"><td class="student-name">${esc(name)}</td><td class="app-cell">Impossible d’analyser : ${esc(state.error)}</td><td>—</td><td>—</td><td><button class="row-btn detail" data-action="detail" data-name="${esc(name)}">Voir les traces</button></td></tr>`;const r=state.report?.subjects?.[subject.value],phrase=r?.phrase||'Pas encore assez de preuves de classe pour proposer une appréciation fiable.',ok=usablePhrase(r),level=r?.suggestedLabel||'À compléter',conf=labelConfidence(r?.confidence);return`<tr data-name="${esc(name)}"><td class="student-name">${esc(name)}</td><td class="app-cell"><textarea class="row-app" data-name="${esc(name)}">${esc(phrase)}</textarea></td><td><span class="level-badge ${esc(r?.suggestedLevel||'')}">${esc(level)}</span></td><td><span class="confidence-badge ${esc(r?.confidence||'insuffisante')}">${esc(conf)}</span></td><td><div class="actions"><button class="row-btn copy" data-action="copy" data-name="${esc(name)}" ${ok?'':'disabled'}>📋 Copier</button><button class="row-btn detail" data-action="detail" data-name="${esc(name)}">Voir le détail</button></div></td></tr>`}
function refreshKpis(){const vals=[...reports.values()].filter(x=>x.report).map(x=>x.report.subjects?.[subject.value]).filter(Boolean);const reliable=vals.filter(usablePhrase).length,check=vals.filter(x=>x.suggestedLevel&&x.confidence!=='elevee'&&x.confidence!=='insuffisante').length,missing=Math.max(0,students.length-reliable);classKpis.innerHTML=`<span class="kpi-pill">${students.length} élèves</span><span class="kpi-pill">${reliable} appréciations exploitables</span><span class="kpi-pill">${check} à vérifier</span><span class="kpi-pill">${missing} à compléter</span>`}
async function analyseOne(name){reports.set(name,{loading:true});const tr=classBody.querySelector(`tr[data-name="${CSS.escape(name)}"]`);if(tr)tr.outerHTML=rowHtml(name,{loading:true});try{const payload=await LSURealConnector.getStudentSnapshot(name),report=LSURealConnector.summarizeSnapshot(payload,{prenom:name,semester:semester.value});snapshots.set(name,payload);reports.set(name,{report});}catch(e){reports.set(name,{error:e.message});}const current=classBody.querySelector(`tr[data-name="${CSS.escape(name)}"]`);if(current)current.outerHTML=rowHtml(name,reports.get(name));refreshKpis();}
async function analyseClass(){if(!students.length){await loadStudents();if(!students.length)return}runClass.disabled=true;reports.clear();snapshots.clear();detail.hidden=true;classBody.innerHTML=students.map(n=>rowHtml(n,{loading:true})).join('');status.textContent=`Analyse de ${students.length} élèves — ${subjectTitle()} — ${semester.value}…`;let cursor=0;const workers=Array.from({length:Math.min(4,students.length)},async()=>{while(cursor<students.length){const name=students[cursor++];await analyseOne(name)}});await Promise.all(workers);runClass.disabled=false;status.textContent=`Analyse terminée — ${subjectTitle()} — ${semester.value}. Les appréciations restent modifiables avant copie.`;refreshKpis()}
function selectedSourceCounts(payload,key,sem){const snap=payload?.snapshot||payload||{},out={A:0,B:0,C:0,D:0};(snap.evaluation_traces||[]).filter(r=>subjectMatches(r,key)&&semesterOf(r)===sem).forEach(r=>{const k=LSUSynthesisEngine.classifyTeachingTrace(r);if(k==='A'||k==='B')out[k]++});(snap.reussites||[]).filter(r=>subjectMatches(r,key)&&semesterOf(r)===sem).forEach(r=>{if(String(r.competence_code||'').trim()&&isHibou(r))out.C++;else out.D++});out.D+=(snap.competences||[]).filter(r=>subjectMatches(r,key)&&(!semesterOf(r)||semesterOf(r)===sem)).length+(snap.records||[]).filter(r=>subjectMatches(r,key)&&(!semesterOf(r)||semesterOf(r)===sem)).length;return out}
function renderSourceCards(payload,key,sem){const counts=selectedSourceCounts(payload,key,sem),defs=[['A','Évaluations de référence','Preuves principales pour le LSU.'],['B','Observations de classe','Cahier du jour, exercices, productions courtes…'],['C','Compétences réussies dans Maître Hibou','Traces complémentaires, jamais décisionnelles seules.'],['D','Autres réussites enregistrées','Médailles, records et informations conservées.']];sources.innerHTML=defs.map(([k,t,d])=>`<article class="source-card"><strong>${counts[k]||0}</strong><span>${t}</span><p>${d}</p></article>`).join('')}
function collectHistory(payload,key){const snap=payload?.snapshot||payload||{},rows=[...(snap.evaluation_traces||[]),...(snap.reussites||[])].filter(r=>subjectMatches(r,key));const seen=new Set();return rows.filter(r=>String(r.competence_code||'').trim()).filter(r=>{const id=String(r.trace_id||r.event_id||[r.date,r.competence_code,r.activite,r.score,r.source].join('|'));if(seen.has(id))return false;seen.add(id);return true}).sort((a,b)=>Date.parse(b.date||0)-Date.parse(a.date||0));}
function renderHistory(payload,key,sem){const rows=collectHistory(payload,key);if(!rows.length){history.innerHTML='<div class="history-empty">Aucune compétence canonique enregistrée pour cette matière.</div>';return}history.innerHTML=`<div class="history-list">${rows.map(r=>{const code=String(r.competence_code||'').trim(),s=semesterOf(r),used=s===sem,other=s&&s!==sem;let badge='<span class="trace-badge neutral">Trace enregistrée</span>';if(used&&isHibou(r))badge='<span class="trace-badge neutral">Trace complémentaire '+esc(sem)+'</span>';else if(used)badge='<span class="trace-badge used">Utilisée pour '+esc(sem)+'</span>';else if(other&&isSuccess(r))badge='<span class="trace-badge report">👏 À reporter au '+esc(s)+'</span>';else if(other)badge='<span class="trace-badge report">À prendre en compte au '+esc(s)+'</span>';return`<div class="trace-row"><div class="trace-date">${esc(formatDate(r.date))}</div><div class="trace-main"><strong>${esc(code+' — '+traceLabel(r))}</strong><span>${esc(r.mastery_status||r.niveau_lsu||r.niveau_suivi||r.resultat||'')}</span></div><div class="trace-source">${sourceLabel(r)}${r.score!==''&&r.score!=null?` · ${esc(r.score)}/${esc(r.total||'—')}`:''}</div><div>${badge}</div></div>`}).join('')}</div>`}
function renderProof(r,payload,sem,key){const coded=collectHistory(payload,key),used=coded.filter(x=>semesterOf(x)===sem),other=coded.filter(x=>semesterOf(x)&&semesterOf(x)!==sem);semesterProof.innerHTML=`<h3>Ce que le moteur peut réellement utiliser pour ${esc(sem)}</h3><ul><li><strong>${used.length}</strong> trace(s) canonique(s) rattachée(s) au semestre affiché.</li><li><strong>${other.length}</strong> trace(s) canonique(s) déjà enregistrée(s) pour l’autre semestre : elles restent visibles ci-dessous sans entrer dans le calcul du semestre courant.</li><li>Les anciennes traces non codées restent conservées dans le Google Sheet mais sont masquées dans cette vue pédagogique.</li><li><strong>Positionnement proposé :</strong> ${esc(r?.suggestedLabel||'pas encore assez de preuves de classe')}.</li></ul>`}
async function openDetail(name){let state=reports.get(name);if(!state?.report){await analyseOne(name);state=reports.get(name)}const report=state?.report;if(!report){return}let payload=snapshots.get(name);if(!payload){try{payload=await LSURealConnector.getStudentSnapshot(name);snapshots.set(name,payload)}catch(e){payload=null}}const r=report.subjects?.[subject.value];detail.hidden=false;detailTitle.textContent=`${name} — ${subjectTitle()} — ${semester.value}`;detailApp.value=r?.phrase||'Pas encore assez de preuves de classe pour proposer une appréciation fiable.';$('copyDetail').disabled=!usablePhrase(r);detailPos.innerHTML=`<div class="big-level">${esc(r?.suggestedLabel||'Pas encore assez de preuves de classe')}</div><p><strong>Confiance :</strong> ${esc(labelConfidence(r?.confidence))}</p><p><strong>Tendance :</strong> ${esc(r?.trend||'insuffisante')}</p><p><strong>Couverture LSU :</strong> ${esc(r?.coverage?.documented||0)}/${esc(r?.coverage?.total||0)} compétence(s) avec preuve enseignante suffisante.</p>${(r?.vigilances||[]).length?`<p><strong>Vigilance :</strong> ${esc(r.vigilances.map(v=>v.group||v.label||v.code).join(', '))}</p>`:''}`;if(payload)renderSourceCards(payload,subject.value,semester.value);else sources.innerHTML='';if(payload){renderProof(r,payload,semester.value,subject.value);renderHistory(payload,subject.value,semester.value)}else{semesterProof.innerHTML='<p>Impossible de charger les traces détaillées.</p>';history.innerHTML=''}detail.scrollIntoView({behavior:'smooth',block:'start'})}
classBody.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const name=b.dataset.name;if(b.dataset.action==='copy'){const ta=classBody.querySelector(`textarea.row-app[data-name="${CSS.escape(name)}"]`);if(ta)copyText(ta.value,b)}else openDetail(name)});
$('copyDetail').addEventListener('click',e=>copyText(detailApp.value,e.currentTarget));$('closeDetail').addEventListener('click',()=>{detail.hidden=true});runClass.addEventListener('click',analyseClass);semester.addEventListener('change',()=>{reports.clear();snapshots.clear();detail.hidden=true;classBody.innerHTML='<tr><td colspan="5" class="table-empty">Le semestre a changé. Relance l’analyse de la classe.</td></tr>';classKpis.innerHTML=''});subject.addEventListener('change',()=>{detail.hidden=true;if(reports.size){classBody.innerHTML=students.map(n=>rowHtml(n,reports.get(n)||{})).join('');refreshKpis()}});loadStudents();
})();
