(()=>{
'use strict';
const $=id=>document.getElementById(id), student=$('lsuStudent'), semester=$('lsuSemester'), run=$('lsuRun'), status=$('lsuStatus'), sources=$('lsuSources'), subjects=$('lsuSubjects');
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function cfg(){return window.LSURealConnector?.getBrowserConfig?.()||{url:'',key:''};}
function jsonp(params,timeoutMs=45000){return new Promise((resolve,reject)=>{const c=cfg();if(!c.url||!c.key)return reject(new Error('Connexion Maître Hibou non configurée sur cet appareil.'));const cb='lsuUI_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const end=(err,data)=>{if(done)return;done=true;clearTimeout(timer);try{s.remove()}catch{};try{delete globalThis[cb]}catch{};err?reject(err):resolve(data)};const timer=setTimeout(()=>end(new Error('Délai de connexion dépassé.')),timeoutMs);globalThis[cb]=data=>end(data&&data.ok===false?new Error(data.error||'Réponse invalide'):null,data);const q=new URLSearchParams({...params,device_key:c.key,tablet_key:c.key,key:c.key,callback:cb,_:Date.now()});s.src=c.url+'?'+q.toString();s.onerror=()=>end(new Error('API Maître Hibou indisponible.'));document.head.appendChild(s);});}
async function loadStudents(){status.textContent='Chargement des élèves…';try{const data=await jsonp({action:'get_eleves'}),rows=Array.isArray(data)?data:(data.students||data.eleves||[]);student.innerHTML='<option value="">Choisir un élève</option>'+rows.map(r=>`<option value="${esc(r.prenom||r.name||'')}">${esc(r.prenom||r.name||'')}</option>`).join('');status.textContent=rows.length?`${rows.length} élèves disponibles.`:'Aucun élève trouvé.';}catch(e){status.textContent='Impossible de charger la liste : '+e.message;}}
function labelTrend(v){return({progression:'↗ progression',fragilisation:'↘ fragilisation',stable:'→ stable',fluctuant:'↔ fluctuant',a_confirmer:'à confirmer',insuffisante:'insuffisante'})[v]||v||'—'}
function labelConfidence(v){return({elevee:'élevée',moyenne:'moyenne',faible:'faible',insuffisante:'insuffisante'})[v]||v||'—'}
function render(report){sources.innerHTML=[['A',report.sources.A,'Preuves fortes'],['B',report.sources.B,'Traces formatives'],['C',report.sources.C,'Maître Hibou'],['D',report.sources.D,'Informations']].map(([k,n,t])=>`<article class="source-card"><strong>${n}</strong><span>${k} · ${t}</span></article>`).join('');const vals=Object.values(report.subjects||{});subjects.innerHTML=vals.length?vals.map(r=>{const level=r.suggestedLevel||'';const vig=(r.vigilances||[]).map(v=>esc(v.group||v.code)).join(', ');return `<article class="subject-card"><div class="subject-card__head"><div><h3>${esc(r.subjectTitle)}</h3><div class="subject-meta"><span class="pill">${r.coverage.documented}/${r.coverage.total} documentées</span><span class="pill">${r.profile.solid} solides</span><span class="pill">${r.profile.consolidation} en consolidation</span><span class="pill">${r.profile.priority} priorité</span><span class="pill">Tendance : ${esc(labelTrend(r.trend))}</span><span class="pill">Confiance : ${esc(labelConfidence(r.confidence))}</span></div></div><span class="level ${level?'level--'+level:''}">${esc(r.suggestedLabel||'Données insuffisantes')}</span></div>${vig?`<div class="vigilance">⚠ Vigilance : ${vig}</div>`:''}<p>${esc(r.phrase||'Aucune phrase proposée tant que les données sont insuffisantes.')}</p></article>`}).join(''):'<div class="empty">Aucune matière disponible.</div>';}
run.addEventListener('click',async()=>{const name=student.value;if(!name){status.textContent='Choisis un élève.';return;}run.disabled=true;status.textContent=`Analyse de ${name} — ${semester.value}…`;try{const report=await LSURealConnector.diagnosticStudent(name,semester.value);window.__lastLSUReport=report;render(report);status.textContent=`Synthèse générée en lecture seule pour ${name}. Aucune donnée n’a été modifiée.`;}catch(e){status.textContent='Erreur : '+e.message;}finally{run.disabled=false;}});
loadStudents();
})();
