(()=>{'use strict';
const KEY='progressions_ce2_memos_personnels_v1',$=id=>document.getElementById(id),panel=$('memoNotesPanel'),openBtn=$('memoQuickBtn');if(!panel||!openBtn)return;let showDone=false;
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')||[]}catch(e){return[]}},save=v=>{localStorage.setItem(KEY,JSON.stringify(v));render()},esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={rappel:'📌 Rappel',preparer:'📚 À préparer',eleve:'👤 Élève',idee:'💡 Idée'};
function render(){const all=read(),visible=all.filter(x=>showDone||!x.done).sort((a,b)=>(a.done-b.done)||String(a.date||'9999').localeCompare(String(b.date||'9999'))||String(b.created).localeCompare(String(a.created)));$('memoNotesCount').textContent=`${all.filter(x=>!x.done).length} mémo${all.filter(x=>!x.done).length>1?'s':''} actif${all.filter(x=>!x.done).length>1?'s':''}`;$('memoNotesShowDone').textContent=showDone?'Masquer les terminés':'Afficher les terminés';$('memoNotesList').innerHTML=visible.length?visible.map(x=>`<article class="memo-note-card ${x.done?'is-done':''}" data-id="${esc(x.id)}"><button class="memo-note-check" data-action="toggle" type="button">${x.done?'↩':'✓'}</button><div><span class="memo-note-category">${labels[x.category]||labels.rappel}</span><strong>${esc(x.text)}</strong>${x.student?`<small>Élève : ${esc(x.student)}</small>`:''}${x.date?`<small>Pour le ${new Intl.DateTimeFormat('fr-FR').format(new Date(x.date+'T12:00:00'))}</small>`:''}</div><div class="memo-note-actions"><button data-action="edit" type="button">Modifier</button><button data-action="delete" type="button">Supprimer</button></div></article>`).join(''):'<div class="memo-notes-empty">Aucun mémo dans cette liste.</div>';panel.querySelectorAll('[data-action]').forEach(btn=>btn.onclick=()=>act(btn.closest('[data-id]').dataset.id,btn.dataset.action));}
function act(id,action){let all=read(),x=all.find(n=>n.id===id);if(!x)return;if(action==='toggle')x.done=!x.done;if(action==='delete'&&!confirm('Supprimer ce mémo ?'))return;if(action==='delete')all=all.filter(n=>n.id!==id);if(action==='edit'){const value=prompt('Modifier le mémo :',x.text);if(value===null)return;if(!value.trim())return;x.text=value.trim();x.updated=new Date().toISOString()}save(all)}
function open(){render();panel.classList.remove('hidden');panel.setAttribute('aria-hidden','false');openBtn.setAttribute('aria-expanded','true');document.body.style.overflow='hidden';setTimeout(()=>$('memoNotesText').focus(),50)}function close(){panel.classList.add('hidden');panel.setAttribute('aria-hidden','true');openBtn.setAttribute('aria-expanded','false');document.body.style.overflow=''}
openBtn.onclick=open;$('memoNotesClose').onclick=close;panel.querySelectorAll('[data-memo-notes-close]').forEach(x=>x.onclick=close);$('memoNotesCategory').onchange=e=>$('memoNotesStudentWrap').classList.toggle('hidden',e.target.value!=='eleve');$('memoNotesShowDone').onclick=()=>{showDone=!showDone;render()};$('memoNotesForm').onsubmit=e=>{e.preventDefault();const text=$('memoNotesText').value.trim();if(!text)return;const category=$('memoNotesCategory').value,all=read();all.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),category,text,student:category==='eleve'?$('memoNotesStudent').value.trim():'',date:$('memoNotesDate').value||'',done:false,created:new Date().toISOString()});save(all);e.target.reset();$('memoNotesStudentWrap').classList.add('hidden');$('memoNotesText').focus()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.classList.contains('hidden'))close()});window.addEventListener('storage',e=>{if(e.key===KEY)render()});render();
})();
