(function(){
'use strict';
const KEYS={roster:'progressions_ce2_classe_v1',meta:'progressions_ce2_classe_meta_v1',tracking:'progressions_ce2_suivi_eleves_v1',traces:'progressions_ce2_traces_competences_v1',recent:'progressions_ce2_hibou_reussites_v1',proofs:'progressions_ce2_hibou_preuves_v1',api:'hibou_sync_api_url_v25754',device:'hibou_sync_device_key_v25754',last:'progressions_ce2_sync_last_roster_v3279'};
const ACTIVE_EVALUATION_KEY='progressions_ce2_active_evaluation_v1';
const STUDENT_LABELS={renforcer:'À revoir',encours:'En progrès',acquis:'Réussi',depasse:'Excellent'};
const LEVELS={none:'Non évalué',renforcer:'À renforcer',encours:'En cours',acquis:'Acquis',depasse:'Très bien maîtrisé'};
const LSU={renforcer:'Non atteint',encours:'Partiellement atteint',acquis:'Atteint',depasse:'Dépassé'};
const state={subject:'francais',period:'all',skill:'',view:'skill',filter:'all',student:''};
function activeEvaluation(){try{return JSON.parse(sessionStorage.getItem(ACTIVE_EVALUATION_KEY)||'null')}catch(e){return null}}
function saveActiveEvaluation(v){try{v?sessionStorage.setItem(ACTIVE_EVALUATION_KEY,JSON.stringify(v)):sessionStorage.removeItem(ACTIVE_EVALUATION_KEY)}catch(e){}}
const initialEvaluation=activeEvaluation();
if(initialEvaluation){state.subject=initialEvaluation.subject||state.subject;state.period=initialEvaluation.period||state.period;state.skill=(initialEvaluation.codes||[])[initialEvaluation.index||0]||'';}
let roster=readJson(KEYS.roster,[]),meta=readJson(KEYS.meta,{}),tracking=readJson(KEYS.tracking,{}),traces=readJson(KEYS.traces,[]),recent=readJson(KEYS.recent,[]),proofs=readJson(KEYS.proofs,[]),syncState=roster.length?'cache':'loading';
let traceSyncTimer=null,traceSyncRunning=false;
function readJson(k,f){try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??f}catch(e){return f}}
function writeJson(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function read(k){try{return String(localStorage.getItem(k)||'').trim()}catch(e){return''}}
function write(k,v){try{localStorage.setItem(k,String(v||''))}catch(e){}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function apiConfig(){return{url:read(KEYS.api),key:read(KEYS.device)}}
function configured(){const c=apiConfig();return /^https:\/\/script\.google\.com\/macros\/s\/.+\/exec$/.test(c.url)&&c.key.length>=16}
function jsonp(params){return new Promise((resolve,reject)=>{const c=apiConfig();if(!configured())return reject(new Error('Synchronisation non configurée'));const cb='progressionsFollowup_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const finish=(err,data)=>{if(done)return;done=true;clearTimeout(timer);try{delete window[cb]}catch(e){}s.remove();err?reject(err):resolve(data)};const timer=setTimeout(()=>finish(new Error('Délai de connexion dépassé')),20000);window[cb]=data=>{if(!data||data.ok===false)return finish(new Error(data&&data.error||'Réponse API invalide'));finish(null,data)};const q=new URLSearchParams({...params,device_key:c.key,tablet_key:c.key,callback:cb,_:Date.now()});s.src=c.url+'?'+q;s.onerror=()=>finish(new Error('Réponse JSONP indisponible'));document.head.appendChild(s)})}
function rowsFrom(data,keys){if(Array.isArray(data))return data;if(!data||typeof data!=='object')return[];for(const k of keys){const v=data[k];if(Array.isArray(v))return v;if(v&&typeof v==='object'){const n=rowsFrom(v,keys);if(n.length)return n}}return[]}
function normalizeRoster(rows){const names=[],next={};(Array.isArray(rows)?rows:[]).forEach(item=>{const x=typeof item==='string'?{prenom:item}:item||{},name=String(x.prenom||x.name||'').trim();if(!name)return;names.push(name);const old=meta[norm(name)]||{};next[norm(name)]={prenom:name,sexe:x.sexe||x.Sexe||old.sexe||'',naissance:x.naissance||x.date_naissance||old.naissance||''}});roster=[...new Set(names)].sort((a,b)=>a.localeCompare(b,'fr'));meta=next;writeJson(KEYS.roster,roster);writeJson(KEYS.meta,meta)}
async function refresh(showAlert=false){setBusy(true);try{if(!configured()){syncState=roster.length?'cache':'error';render();if(showAlert)alert('La synchronisation n’est pas configurée sur ce navigateur.');return}const data=await jsonp({action:'get_eleves'});normalizeRoster(Array.isArray(data)?data:data.eleves||[]);syncState='online';write(KEYS.last,new Date().toISOString());await Promise.allSettled([loadRecent(),loadProofs()]);render()}catch(e){syncState=roster.length?'cache':'error';render();if(showAlert)alert('Synchronisation impossible. La copie locale est conservée.\n'+e.message)}finally{setBusy(false)}}
async function loadRecent(){try{const data=await jsonp({action:'reussites',limit:300});recent=rowsFrom(data,['reussites','réussites','achievements','rows','results','data']);writeJson(KEYS.recent,recent)}catch(e){}}
async function loadProofs(){for(const action of ['ceintures','competences']){try{const data=await jsonp({action});const rows=rowsFrom(data,['ceintures','competences','rows','results','data']);if(rows.length){proofs=rows;writeJson(KEYS.proofs,proofs);break}}catch(e){}}}
function setBusy(v){const b=document.getElementById('refreshBtn');b.disabled=v;b.textContent=v?'⏳ Connexion…':'↻ Actualiser'}
function hasCompetencies(obj){if(!obj||!obj.title)return false;if(Array.isArray(obj.domains))return true;return ['p1','p2','p3','p4','p5'].some(p=>Array.isArray(obj[p+'Competencies']))}
function subjects(){const p=window.PROGRESSIONS||{};return Object.entries(p).filter(([,v])=>hasCompetencies(v))}
function normalizeSkill(i,domainFallback=''){return{code:i&&String(i.code||i.id||'').trim(),label:i&&String(i.label||i.title||i.competence||i.text||i.code||'Compétence').trim(),domain:i&&String(i.domain||domainFallback||'').trim()}}
function allSkills(subject=state.subject){const obj=(window.PROGRESSIONS||{})[subject];if(!obj)return[];const out=[];const wanted=state.period;
  // Structure actuelle du référentiel : p1Competencies ... p5Competencies.
  const periods=wanted==='all'?['p1','p2','p3','p4','p5']:[wanted];
  periods.forEach(p=>{const arr=obj[p+'Competencies'];if(Array.isArray(arr))arr.forEach(i=>out.push(normalizeSkill(i))) });
  // Compatibilité avec l'ancienne structure domains/items.
  (obj.domains||[]).forEach(d=>(d.items||[]).forEach(i=>{const ps=Array.isArray(i.periods)?i.periods:[];if(wanted==='all'||ps.includes(wanted)||i.period===wanted||!ps.length)out.push(normalizeSkill(i,d.title||d.label||''))}));
  const seen=new Set();return out.filter(x=>x.code&&!seen.has(x.code)&&(seen.add(x.code),true))}
function key(student,code){return student+'|'+code}
function entry(student,code){return tracking[key(student,code)]||{level:'none',note:'',date:''}}
function pendingTraces(limit=100){return traces.filter(t=>t&&t.trace_id&&t.sync_status!=='synced').slice(0,limit)}
async function readTracesFromSheet(){if(!configured())return false;try{const data=await jsonp({action:'evaluation_traces',limit:5000}),rows=Array.isArray(data)?data:(data&&Array.isArray(data.traces)?data.traces:[]),byId=new Map(traces.map((t,i)=>[String(t&&t.trace_id||''),i]).filter(([id])=>id));rows.forEach(raw=>{const id=String(raw&&raw.trace_id||'').trim();if(!id)return;const normalized={...raw,trace_id:id,sync_status:'synced',sync_error:''};if(byId.has(id))traces[byId.get(id)]={...traces[byId.get(id)],...normalized};else{byId.set(id,traces.length);traces.push(normalized)}});writeJson(KEYS.traces,traces);return true}catch(e){console.warn('Lecture traces LSU :',e);return false}}
async function flushTraces(){if(traceSyncRunning||!configured())return false;const batch=pendingTraces(100);if(!batch.length)return true;traceSyncRunning=true;const c=apiConfig();try{const payload={device_key:c.key,tablet_key:c.key,source:'progressions_ce2',appareil:location.hostname||'local',traces_evaluations:batch.map(t=>({trace_id:t.trace_id,date:t.date,prenom:t.prenom,matiere:t.matiere,periode:t.periode,competence_code:t.competence_code,competence_label:t.competence_label,domaine:t.domaine,niveau_suivi:t.niveau_suivi,libelle_eleve:t.libelle_eleve,niveau_lsu:t.niveau_lsu,source:t.source,evaluation_id:t.evaluation_id,evaluation_titre:t.evaluation_titre,note:t.note||''}))};await fetch(c.url,{method:'POST',mode:'no-cors',cache:'no-store',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(payload)});const ids=new Set(batch.map(t=>t.trace_id));traces.forEach(t=>{if(ids.has(t.trace_id)){t.sync_status='sent';t.sync_error=''}});writeJson(KEYS.traces,traces);setTimeout(()=>readTracesFromSheet(),1600);return true}catch(e){const ids=new Set(batch.map(t=>t.trace_id));traces.forEach(t=>{if(ids.has(t.trace_id)){t.sync_status='pending';t.sync_error=String(e&&e.message||e)}});writeJson(KEYS.traces,traces);return false}finally{traceSyncRunning=false}}
function queueTraceSync(){clearTimeout(traceSyncTimer);traceSyncTimer=setTimeout(flushTraces,700)}
function evaluationContext(code){const ctx=activeEvaluation();if(!ctx||!Array.isArray(ctx.codes)||!ctx.codes.includes(code))return null;if(ctx.subject&&ctx.subject!==state.subject)return null;if(ctx.period&&ctx.period!==state.period)return null;return ctx}
function saveEntry(student,code,level){const old=entry(student,code).level||'none',date=new Date().toISOString(),ctx=evaluationContext(code);tracking[key(student,code)]={...entry(student,code),level,date};writeJson(KEYS.tracking,tracking);if(old!==level&&level!=='none'){const skill=allSkills().find(s=>s.code===code)||{code,label:code,domain:''};traces.push({trace_id:'trace-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),date,prenom:student,matiere:state.subject,periode:state.period,competence_code:code,competence_label:skill.label,domaine:skill.domain,niveau_suivi:level,libelle_eleve:ctx?(STUDENT_LABELS[level]||LEVELS[level]):LEVELS[level],niveau_lsu:LSU[level]||'',source:ctx?'evaluation_papier':'observation_classe',evaluation_id:ctx&&ctx.id||'',evaluation_titre:ctx&&ctx.title||'',note:entry(student,code).note||'',sync_status:'pending',sync_error:''});writeJson(KEYS.traces,traces);queueTraceSync()}render()}
function eventStudent(r){return String(r&&(r.prenom||r.eleve||r.name||r.student)||'').trim()}
function eventTime(r){const t=new Date(r&&(r.date||r.timestamp||r.datetime||r.created_at||r.createdAt)||0).getTime();return Number.isFinite(t)?t:0}
function activityText(r){return String(r&&(r.texte||r.text||r.detail||r.activite||r.competence||r.ceinture)||'Activité Maître Hibou').trim()}
function recentFor(name){return recent.filter(r=>norm(eventStudent(r))===norm(name)).sort((a,b)=>eventTime(b)-eventTime(a))}
function portrait(name){const s=norm((meta[norm(name)]||{}).sexe);if(s.startsWith('f'))return'assets/portraits/portrait_fille.png';if(s.startsWith('g')||s.startsWith('m'))return'assets/portraits/portrait_garcon.png';return'assets/portraits/portrait_neutre.png'}
function summary(){const code=state.skill,counts={none:0,renforcer:0,encours:0,acquis:0,depasse:0};roster.forEach(n=>counts[entry(n,code).level||'none']++);const priority=roster.filter(n=>allSkills().filter(s=>entry(n,s.code).level==='renforcer').length>=2).length;const recentCount=roster.filter(n=>{const x=recentFor(n)[0];return x&&Date.now()-eventTime(x)<=7*86400000}).length;return{counts,priority,recent:recentCount}}
function priorityItems(){const skills=allSkills(),items=[];roster.forEach(name=>{const selected=entry(name,state.skill).level||'none',fragile=skills.filter(s=>entry(name,s.code).level==='renforcer'),activity=recentFor(name)[0],days=activity?Math.floor((Date.now()-eventTime(activity))/86400000):999;let type='';let reason='';if(selected==='renforcer'){type='renforcer';reason='À renforcer pour la compétence sélectionnée'}else if(selected==='none'){type='none';reason='Pas encore évalué pour la compétence sélectionnée'}else if(fragile.length>=2){type='priority';reason=fragile.length+' compétences à renforcer'}else if(days<=7){type='recent';reason='Progrès récent : '+activityText(activity)}if(type)items.push({name,type,reason,time:eventTime(activity),fragile:fragile.length})});if(state.filter!=='all')return items.filter(i=>i.type===state.filter);const order={renforcer:0,priority:1,none:2,recent:3};return items.sort((a,b)=>(order[a.type]-order[b.type])||b.fragile-a.fragile||b.time-a.time).slice(0,14)}
function renderPriorities(){const box=document.getElementById('priorityList'),items=priorityItems();document.getElementById('clearFilterBtn').hidden=state.filter==='all';if(!items.length){box.innerHTML='<div class="empty-note">Aucune priorité ne correspond à ce filtre.</div>';return}box.innerHTML=items.map(i=>{const cls=i.type==='recent'?'green':i.type==='none'?'yellow':'red',label=i.type==='recent'?'Progrès':i.type==='none'?'À évaluer':'Priorité';return'<article class="priority-item"><img src="'+portrait(i.name)+'" alt=""><div class="priority-copy"><strong>'+esc(i.name)+'</strong><span>'+esc(i.reason)+'</span><div class="priority-actions"><button type="button" data-open-student="'+esc(i.name)+'">Ouvrir le parcours</button><button type="button" data-detail-student="'+esc(i.name)+'">Voir le suivi</button></div></div><span class="priority-badge '+cls+'">'+label+'</span></article>'}).join('');box.querySelectorAll('[data-open-student]').forEach(b=>b.onclick=()=>window.ParcoursOutil?.openForStudent(b.dataset.openStudent));box.querySelectorAll('[data-detail-student]').forEach(b=>b.onclick=()=>{state.student=b.dataset.detailStudent;state.view='student';document.getElementById('detailPanel').open=true;renderDetail();document.getElementById('detailPanel').scrollIntoView({behavior:'smooth'})})}
function renderGroups(){const groups=[['À reprendre','renforcer'],['À observer','none'],['Consolidation','encours'],['Autonomie','acquis']];document.getElementById('groupsList').innerHTML=groups.map(([title,level])=>{const names=roster.filter(n=>(entry(n,state.skill).level||'none')===level);return'<article class="group-card"><strong>'+title+' · '+names.length+'</strong><span>'+LEVELS[level]+'</span><span class="group-names">'+(names.length?names.map(esc).join(', '):'Aucun élève')+'</span></article>'}).join('')}
function periodLabel(){return state.period==='all'?'Vue annuelle':'Période '+String(state.period).replace('p','')}
function subjectTitle(){return ((window.PROGRESSIONS||{})[state.subject]||{}).title||state.subject}
function displayLevels(){const ctx=evaluationContext(state.skill);return ctx?{none:'— Non renseigné —',renforcer:'🔴 À revoir',encours:'🟡 En progrès',acquis:'✅ Réussi',depasse:'🌟 Excellent'}:LEVELS}
function evaluationBanner(){const ctx=evaluationContext(state.skill);if(!ctx)return'';const available=(ctx.codes||[]).filter(code=>allSkills().some(s=>s.code===code));let i=available.indexOf(state.skill);if(i<0)i=0;return '<div class="evaluation-active-banner"><div><strong>📝 '+esc(ctx.title||'Évaluation active')+'</strong><span>Compétence '+(i+1)+' / '+available.length+' · correction rapide : Excellent / Réussi / En progrès / À revoir</span></div><div><button type="button" data-eval-prev '+(i<=0?'disabled':'')+'>← Précédente</button><button type="button" data-eval-next '+(i>=available.length-1?'disabled':'')+'>Suivante →</button><button type="button" data-eval-stop>Terminer</button></div></div>'}
function bindEvaluationNav(){const ctx=evaluationContext(state.skill);if(!ctx)return;const available=(ctx.codes||[]).filter(code=>allSkills().some(s=>s.code===code)),i=available.indexOf(state.skill);document.querySelector('[data-eval-prev]')?.addEventListener('click',()=>{if(i>0){state.skill=available[i-1];ctx.index=i-1;saveActiveEvaluation(ctx);render()}});document.querySelector('[data-eval-next]')?.addEventListener('click',()=>{if(i>=0&&i<available.length-1){state.skill=available[i+1];ctx.index=i+1;saveActiveEvaluation(ctx);render()}});document.querySelector('[data-eval-stop]')?.addEventListener('click',()=>{saveActiveEvaluation(null);render()})}
function skillContextHtml(skill){const title=skill?skill.label:'Compétence non sélectionnée',domain=skill&&skill.domain?skill.domain:'Domaine non précisé',code=skill&&skill.code?skill.code:'';return '<div class="skill-context"><div><span class="eyebrow">COMPÉTENCE OBSERVÉE</span><h3>'+esc(title)+'</h3><p>'+esc(subjectTitle())+' · '+esc(periodLabel())+' · '+esc(domain)+(code?' · '+esc(code):'')+'</p></div><button type="button" class="change-skill-btn" data-change-skill>Changer de compétence</button></div>'}
function bindChangeSkill(){document.querySelectorAll('[data-change-skill]').forEach(b=>b.onclick=()=>{const select=document.getElementById('skillSelect');select.focus();select.scrollIntoView({behavior:'smooth',block:'center'})})}
function renderSkillView(){const code=state.skill,skill=allSkills().find(s=>s.code===code),levels=displayLevels(),rows=roster.map(name=>'<tr><td><strong>'+esc(name)+'</strong></td><td><select class="level-select" data-level-student="'+esc(name)+'">'+Object.entries(levels).map(([v,l])=>'<option value="'+v+'" '+((entry(name,code).level||'none')===v?'selected':'')+'>'+l+'</option>').join('')+'</select></td><td><button type="button" data-open-student="'+esc(name)+'">Parcours</button></td></tr>').join('');document.getElementById('skillView').innerHTML=evaluationBanner()+skillContextHtml(skill)+'<h4 class="tracking-subtitle">Suivi de la compétence</h4><table class="tracking-table"><thead><tr><th>Élève</th><th>Niveau</th><th></th></tr></thead><tbody>'+rows+'</tbody></table>';document.querySelectorAll('[data-level-student]').forEach(s=>s.onchange=()=>saveEntry(s.dataset.levelStudent,code,s.value));document.querySelectorAll('#skillView [data-open-student]').forEach(b=>b.onclick=()=>window.ParcoursOutil?.openForStudent(b.dataset.openStudent));bindChangeSkill();bindEvaluationNav()}
function renderStudentView(){const select=document.getElementById('studentSelect');select.innerHTML=roster.map(n=>'<option '+(n===state.student?'selected':'')+'>'+esc(n)+'</option>').join('');if(!state.student)state.student=roster[0]||'';select.value=state.student;const skills=allSkills(),selectedSkill=skills.find(s=>s.code===state.skill),counts={none:0,renforcer:0,encours:0,acquis:0,depasse:0};skills.forEach(s=>counts[entry(state.student,s.code).level||'none']++);document.getElementById('studentSummary').innerHTML=skillContextHtml(selectedSkill)+'<div class="student-summary-grid">'+Object.entries(counts).map(([k,v])=>'<article class="student-summary-card"><strong>'+v+'</strong><span>'+LEVELS[k]+'</span></article>').join('')+'</div><div class="student-skills">'+skills.map(s=>'<div class="student-skill"><span>'+esc(s.label)+'</span><b>'+LEVELS[entry(state.student,s.code).level||'none']+'</b></div>').join('')+'</div>';bindChangeSkill()}
function renderDetail(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('is-active',b.dataset.view===state.view));document.getElementById('skillView').hidden=state.view!=='skill';document.getElementById('studentView').hidden=state.view!=='student';state.view==='skill'?renderSkillView():renderStudentView()}
function renderSelectors(){const ss=document.getElementById('subjectSelect'),subjectsList=subjects();ss.innerHTML=subjectsList.map(([k,v])=>'<option value="'+k+'" '+(k===state.subject?'selected':'')+'>'+esc(v.title)+'</option>').join('');const skills=allSkills();if(!skills.some(s=>s.code===state.skill))state.skill=skills[0]?.code||'';document.getElementById('skillSelect').innerHTML=skills.map(s=>'<option value="'+esc(s.code)+'" '+(s.code===state.skill?'selected':'')+'>'+esc(s.label)+'</option>').join('')}
function syncText(){const last=new Date(read(KEYS.last)||0).getTime(),source=syncState==='online'?'Google Sheets':syncState==='cache'?'copie locale':'connexion indisponible';return roster.length+' élève'+(roster.length>1?'s':'')+' · '+source+' · dernière actualisation : '+(last?new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(last):'jamais')}
function render(){renderSelectors();const s=summary();document.getElementById('kpiRenforcer').textContent=s.counts.renforcer;document.getElementById('kpiNone').textContent=s.counts.none;document.getElementById('kpiPriority').textContent=s.priority;document.getElementById('kpiRecent').textContent=s.recent;document.getElementById('syncStatus').textContent=syncText();renderPriorities();renderGroups();renderDetail()}
document.getElementById('subjectSelect').onchange=e=>{state.subject=e.target.value;state.skill='';render()};document.getElementById('periodSelect').onchange=e=>{state.period=e.target.value;state.skill='';render()};document.getElementById('skillSelect').onchange=e=>{state.skill=e.target.value;state.filter='all';render()};document.querySelectorAll('[data-kpi]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.kpi;document.querySelectorAll('[data-kpi]').forEach(x=>x.classList.toggle('is-active',x===b));renderPriorities()});document.getElementById('clearFilterBtn').onclick=()=>{state.filter='all';document.querySelectorAll('[data-kpi]').forEach(x=>x.classList.remove('is-active'));renderPriorities()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;renderDetail()});document.getElementById('studentSelect').onchange=e=>{state.student=e.target.value;renderStudentView()};document.getElementById('refreshBtn').onclick=()=>refresh(true);document.getElementById('printBtn').onclick=()=>window.print();document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({version:'33.00',tracking,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='suivi_ce2_v33_00.json';a.click();URL.revokeObjectURL(a.href)};document.getElementById('copyGroupsBtn').onclick=async()=>{const text=[...document.querySelectorAll('.group-card')].map(c=>c.innerText).join('\n\n');try{await navigator.clipboard.writeText(text);alert('Composition des groupes copiée.')}catch(e){alert(text)}};
render();if(initialEvaluation){document.getElementById('detailPanel').open=true;setTimeout(()=>document.getElementById('detailPanel').scrollIntoView({behavior:'instant',block:'start'}),30)}if(configured()){refresh(false);readTracesFromSheet().then(()=>{if(pendingTraces(1).length)queueTraceSync()})};
})();
