(function(){
'use strict';
const $=id=>document.getElementById(id), EDT=window.PUBLIC_EDT;
const PUBLISHED_PROGRAMMES=window.REMPLACANT_PROGRAMMES||{};
const PUBLISHED_CAHIER=window.REMPLACANT_CAHIER||{sessionMeta:{},pedagogyPrefs:{},summaries:{}};
const PUBLISHED_INFOS=window.REMPLACANT_INFOS||{};
const DEVOIRS=window.DEVOIRS_P1||{weeks:[]};
const defaults={schoolHours:'9h00–12h00 / 14h00–17h00',breaks:'10h45–11h00 / 15h45–16h00',duties:'Consulter les indications laissées sur le bureau ou dans le cahier journal.',dismissal:'Vérifier les habitudes de sortie, cantine et prises en charge indiquées pour la journée.',materials:'Les cahiers, manuels et outils habituels sont ceux utilisés dans le cahier journal et l’emploi du temps.',other:'En cas de doute, se rapprocher de la direction ou d’un collègue de l’école.'};
let weekOffset=0,journalMode='today';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function frDate(d,opts={weekday:'long',day:'numeric',month:'long',year:'numeric'}){return new Intl.DateTimeFormat('fr-FR',opts).format(d).replace(/^./,c=>c.toUpperCase())}
function rowsForDate(date){return EDT.rowsForDate(date,{programmes:PUBLISHED_PROGRAMMES})}
function subjectLabel(row){return row[1]||'Activité'} function detailLabel(row){return row[2]||row[3]||''}
function renderToday(){const now=new Date(),data=rowsForDate(now);$('todayDate').textContent=frDate(now);$('periodBadge').textContent=EDT.periodLabel(data.period).toUpperCase();$('todayStatus').textContent=data.rows.length?`${data.rows.length} temps prévu(s) · ${data.source}`:'Pas de classe prévue aujourd’hui. L’emploi du temps de la période reste accessible ci-dessous.';$('todayTimeline').innerHTML=data.rows.length?data.rows.map(r=>`<article class="timeline-item"><div class="timeline-item__time">${esc(r[0])}</div><div><strong>${esc(subjectLabel(r))}</strong><small>${esc(detailLabel(r))}</small></div></article>`).join(''):'<div class="timeline-empty">Aucune journée de classe aujourd’hui.</div>'}
function renderWeek(){const monday=EDT.addDays(EDT.mondayOf(new Date()),weekOffset*7),days=[0,1,3,4].map(n=>EDT.addDays(monday,n));$('weekLabel').textContent=`Du ${frDate(monday,{day:'numeric',month:'long'})} au ${frDate(EDT.addDays(monday,4),{day:'numeric',month:'long',year:'numeric'})}`;$('weekSchedule').innerHTML=days.map(d=>{const data=rowsForDate(d);return `<section class="day-card"><h3>${esc(frDate(d,{weekday:'long',day:'numeric',month:'long'}))}</h3><p class="day-source">${esc(data.source)}</p>${data.rows.length?data.rows.map(r=>`<div class="day-row"><time>${esc(r[0])}</time><div><strong>${esc(subjectLabel(r))}</strong><small>${esc(detailLabel(r))}</small></div></div>`).join(''):'<div class="empty-note">Pas de classe prévue.</div>'}</section>`}).join('')}
function sessionKey(date,row,index){return [EDT.iso(date),row[0]||'',row[1]||'',row[2]||'',index+1].join('|')}
function journalMeta(date,row,index){const metas=PUBLISHED_CAHIER.sessionMeta||{},peds=PUBLISHED_CAHIER.pedagogyPrefs||{},k=sessionKey(date,row,index);return{meta:metas[k]||{},ped:peds[k]||{}}}
function renderJournalDay(date){const data=rowsForDate(date);if(!data.rows.length)return `<div class="empty-note">Aucune séance enregistrée pour ${esc(frDate(date))}.</div>`;return `<section class="journal-day"><h3>${esc(frDate(date))}</h3>${data.rows.map((r,i)=>{const x=journalMeta(date,r,i),activity=x.meta.activity||subjectLabel(r),domain=x.meta.subdomain||'',objective=x.ped.objective||'',competence=x.ped.competence||r[3]||'',remark=x.meta.remark||'';return `<div class="journal-entry"><time>${esc(r[0])}</time><div class="journal-entry__domain">${esc(domain||r[1]||'')}</div><div class="journal-entry__body"><strong>${esc(activity)}</strong>${objective?`<p><b>Objectif :</b> ${esc(objective)}</p>`:''}${competence?`<p><b>Compétence :</b> ${esc(competence)}</p>`:''}${remark?`<p><b>Remarque :</b> ${esc(remark)}</p>`:''}</div></div>`}).join('')}</section>`}
function journalSummary(monday){const v=(PUBLISHED_CAHIER.summaries||{})[EDT.iso(monday)]||{},pairs=[['Apprentissages réalisés',v.learned],['Séances reportées',v.deferred],['À reprendre',v.review],['Événements particuliers',v.events],['Absences / changements',v.changes],['À prévoir',v.next]].filter(x=>x[1]);$('journalSummary').innerHTML=pairs.length?`<h3>Notes de la semaine</h3><dl>${pairs.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`:'<span class="section-kicker">Notes de la semaine</span><p>Aucune note complémentaire publiée.</p>'}
function renderJournal(){const monday=EDT.mondayOf(new Date());$('journalTodayBtn').classList.toggle('is-active',journalMode==='today');$('journalWeekBtn').classList.toggle('is-active',journalMode==='week');$('journalContent').innerHTML=journalMode==='today'?renderJournalDay(new Date()):[0,1,3,4].map(n=>renderJournalDay(EDT.addDays(monday,n))).join('');journalSummary(monday)}
function portraitFor(s){const v=norm(s.sexe);if(v.startsWith('f'))return'assets/portraits/portrait_fille.png';if(v.startsWith('g')||v.startsWith('m'))return'assets/portraits/portrait_garcon.png';return'assets/portraits/portrait_neutre.png'}
function rosterRows(){const raw=Array.isArray(window.REMPLACANT_ELEVES)?window.REMPLACANT_ELEVES:[];return raw.map(x=>typeof x==='string'?{prenom:String(x).trim()}:{...x,prenom:String(x&&x.prenom||'').trim()}).filter(x=>x.prenom).sort((a,b)=>String(a.prenom).localeCompare(String(b.prenom),'fr',{sensitivity:'base'}))}
function renderStudents(){const rows=rosterRows();$('studentSummary').textContent=rows.length?`${rows.length} élève${rows.length>1?'s':''}`:'Liste de classe';$('studentCountTitle').textContent=rows.length?`— ${rows.length}`:'';$('studentList').innerHTML=rows.length?rows.map((s,i)=>`<article class="student-item"><img src="${portraitFor(s)}" alt=""><div><strong>${i+1}. ${esc(s.prenom)}${s.initiale?' '+esc(s.initiale):''}</strong><small>${s.cham?'🎵 CHAM':'Élève de la classe'}</small></div></article>`).join(''):'<div class="empty-note">La liste statique de la classe n’a pas encore été renseignée.</div>';$('studentSyncState').textContent=rows.length?`Liste intégrée · ${rows.length} élève${rows.length>1?'s':''}`:'Liste à renseigner'}

function isoLocal(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function dateFromIso(s){const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d)}
function homeworkWeekFor(date){const iso=isoLocal(date),weeks=Array.isArray(DEVOIRS.weeks)?DEVOIRS.weeks:[];return weeks.find(w=>iso>=w.start&&iso<=w.end)||(iso<'2026-09-01'?weeks[0]:weeks[weeks.length-1])||null}
function homeworkRow(it){return `<article class="replacement-homework-card"><div class="replacement-homework-date">Pour ${esc(frDate(dateFromIso(it.due),{weekday:'long',day:'numeric',month:'long'}))}</div><p><b>${esc(it.routineIcon||'📚')} ${esc(it.routineTitle||'Je revois')} :</b> ${esc(it.routine||'')}</p>${it.challenge?`<p><b>🎯 Défi :</b> ${esc(it.challenge)}</p>`:''}${it.family?`<p class="replacement-family"><b>👨‍👩‍👧 Défi famille — facultatif :</b> ${esc(it.family)}</p>`:''}<small><b>Notion consolidée :</b> ${esc(it.notion||'')}</small>${it.hibou?`<small> · 🦉 Maître Hibou : ${esc(it.hibou)}</small>`:''}</article>`}
function renderHomework(){const week=homeworkWeekFor(new Date()),box=$('replacementHomework'),all=$('replacementHomeworkAll');if(!box||!all)return;if(!week){box.innerHTML='<div class="empty-note">Aucun devoir programmé.</div>';return}box.innerHTML=`<div class="replacement-homework-head"><strong>${esc(week.label||'')}</strong><span>${esc(week.theme||'')}</span></div>${week.note?`<div class="empty-note">${esc(week.note)}</div>`:(week.items||[]).map(homeworkRow).join('')}${week.holiday?`<div class="replacement-holiday">🏖️ ${esc(week.holiday)}</div>`:''}`;all.innerHTML=(DEVOIRS.weeks||[]).map(w=>`<section class="replacement-homework-week"><h3>${esc(w.label)} · ${esc(frDate(dateFromIso(w.start),{day:'numeric',month:'long'}))} → ${esc(frDate(dateFromIso(w.end),{day:'numeric',month:'long'}))}</h3><p>${esc(w.theme||'')}</p>${w.note?`<div class="empty-note">${esc(w.note)}</div>`:(w.items||[]).map(homeworkRow).join('')}${w.holiday?`<div class="replacement-holiday">🏖️ ${esc(w.holiday)}</div>`:''}</section>`).join('')}

function renderPractical(){const v={...defaults,...PUBLISHED_INFOS},cards=[['🕘 Horaires de l’école',v.schoolHours],['☕ Récréations',v.breaks],['🦺 Services',v.duties],['🚪 Sortie / cantine',v.dismissal],['📚 Outils et matériel',v.materials],['📝 Autres informations',v.other]];$('practicalView').innerHTML=cards.map(([h,p])=>`<article class="info-card"><h3>${h}</h3><p>${esc(p)}</p></article>`).join('')}
function bindDialogs(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const d=$(b.dataset.open+'Dialog');if(b.dataset.open==='schedule')renderWeek();if(b.dataset.open==='journal')renderJournal();if(b.dataset.open==='students')renderStudents();if(b.dataset.open==='practical')renderPractical();if(b.dataset.open==='homework')renderHomework();d.showModal()});document.querySelectorAll('.sub-dialog').forEach(d=>{d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close()})})}
function init(){if(!EDT){document.body.innerHTML='<p>Emploi du temps local indisponible.</p>';return}renderToday();renderPractical();renderStudents();renderHomework();bindDialogs();$('prevWeek').onclick=()=>{weekOffset--;renderWeek()};$('nextWeek').onclick=()=>{weekOffset++;renderWeek()};$('journalTodayBtn').onclick=()=>{journalMode='today';renderJournal()};$('journalWeekBtn').onclick=()=>{journalMode='week';renderJournal()}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
